condition = 'condition'
activity = 'activity'
state = 'state'
others = 'others'
META = {
    'alone': condition,
    'at petrol/gas station': activity,
    'biking': state,
    'laborer': others,
    'couple': condition,
    'dining': activity,
    'gsv car interaction': activity,
    'group': condition,
    'on wheelchair': state,
    'pet interactions': activity,
    'phone interaction': activity,
    'playing': activity,
    'pushing stroller or shopping cart': activity,
    "pushing stroller": activity,
    "pushing shopping cart": activity,
    'pushing wheelchair': activity,
    'running': state,
    'shopping': activity,
    'sitting': state,
    'sport activities': activity,
    'standing': state,
    'vendor': others,
    'taking photo': activity,
    'talking': activity,
    'talking on phone': activity,
    'waiting in bus station': activity,
    'walking': state,
    'with bike': others,
    'with coffee or drinks': others,
    'baby': others,
    'crossing crosswalk': activity,
    'duplicate': others,
    'elderly': others,
    'kid': others,
    'mobility aids': others,
    'model_hint': others,
    'no people': condition,
    'not sure': others,
    'pet': others,
    'cleaning': activity,
    'riding carriage': state,
    'teenager': others,
    'working/laptop': activity,
    'no interaction': activity,
    'multi-label': others,
    'police': others,
    'unloading packages': activity,
    'reading': activity,
    'waiting for food': activity,
    'taking cab': activity,
    'picnic': activity,
    'with luggage': others,
    'riding motorcycle': state,
    'hugging': activity,
}
