NATURAL = {
    'alone': 'a person alone',
    'pedestrian': 'a pedestrian',
    'individual': 'an individual',
    'person': 'a person',
    'at petrol station': 'at a petrol station',
    'at gas station': 'at a gas station',
    'biking': 'biking',
    'bicycling': 'bicycling',
    'construction-worker': 'a construction-worker',
    'construction-workers': 'construction-workers',
    'builders': 'builders',
    'couple': 'a couple',
    'two people': 'two people',
    'two pedestrians': 'two pedestrians',
    'dining': 'dining',
    'eating': 'eating',
    'car interaction': 'a car interaction',
    'group': 'a group',
    'people': 'people',
    'gathering': 'a gathering',
    'on wheelchair': 'on a wheelchair',
    'riding wheelchair': 'riding a wheelchair',
    'pet interactions': 'pet interactions',
    'using phone': 'using a phone',
    'on phone': 'on a phone',
    'playing': 'playing',
    'pushing stroller': 'pushing a stroller',
    'pushing baby carriage': 'pushing a baby carriage',
    'pushing shopping cart': 'pushing a shopping cart',
    # 'pushing stroller or shopping cart': 'pushing a stroller or pushing a shopping cart',
    'running': 'running',
    'jogging': 'jogging',
    'shopping': 'shopping',
    'browsing': 'browsing',
    'sitting': 'sitting',
    'sitting on bench': 'sitting on a bench',
    'sitting on chair': 'sitting on a chair',
    'seated': 'seated',
    'playing sports': 'playing sports',
    'sports': 'doing sports',
    'standing': 'standing',
    'standing up': 'standing up',
    'street-vendors': 'street-vendors',
    'street-merchant': 'a street-merchant',
    'street-merchants': 'street-merchants',
    'street-vendor': 'a street-vendor',
    'taking picture': 'taking a picture',
    'photographing': 'photographing',
    'talking': 'talking',
    'chatting': 'chatting',
    'talking on phone': 'talking on a phone',
    'chatting on phone': 'chatting on a phone',
    'waiting for the bus': 'waiting for a bus',
    'waiting at bus station': 'waiting at a bus station',
    'walking': 'walking',
    'strolling': 'strolling',
    'with bike': 'with a bike',
    'with bicycle': 'with a bicycle',
    'with drink': 'with a drink',
    'with beverage': 'with a beverage',
    'with dog': 'with a dog',
    'with pet': 'with a pet',
    'baby': 'a baby',
    'infant': 'an infant',
    'crossing street': 'crossing a street',
    'crossing road': 'crossing a road',
    'duplicate': 'a duplicate',
    'duplicated': 'duplicated',
    'elderly': 'an elderly person',
    'senior': 'a senior',
    'kid': 'a kid',
    'child': 'a child',
    'walking aids': 'with walking aids',
    'walking stick': 'with a walking stick',
    'model_hint': 'model_hint',
    'multi-label': 'multi-label',
    'no people': 'no people',
    'not sure': 'not sure',
    'confusing': 'confusing',
    'ambiguous': 'ambiguous',
    'pet': 'a pet',
    'service dog': 'a service dog',
    'public service': 'public service',
    'cleaning': 'cleaning',
    'riding carriage': 'riding a carriage',
    'riding horse carriage': 'riding a horse carriage',
    'teenager': 'a teenager',
    'teen': 'a teen',
    'working on laptop': 'working on a laptop',
    'working on computer': 'working on a computer',
    'no interaction': 'no interaction',
    'police': 'police',
    'law enforcement': 'law enforcement',
    'loading packages': 'loading packages',
    'unloading packages': 'unloading packages',
    'reading': 'reading',
    'reading book': 'reading a book',
    'with luggage': 'with luggage',
    'with suitcase': 'with a suitcase',
    'waiting for food': 'waiting for food',
    'waiting for drink': 'waiting for a drink',
    'taking taxi': 'taking a taxi',
    'taking cab': 'taking a cab',
    'picnic': 'picnic',
    'picnicking': 'picnicking',
    'riding motorcycle': 'riding a motorcycle',
    'motorcycling': 'motorcycling',
    'hugging': 'hugging',
    'embracing': 'embracing',
    'sitting on bench or chair': 'sitting on a bench or chair',
    'standing to cross crosswalk': 'standing to cross a crosswalk',
    'seated on bench or chair': 'seated on a bench or chair',
    'a person': 'person',
    'at petrol/gas station': 'at petrol station',
    'riding bicycle': 'bicycling',
    'riding bike': 'biking',
    'cycling': 'bicycling',
    'laborers': 'construction workers',
    'two friends': 'two people',
    'couple/2people': 'couple',
    'snacking': 'eating',
    'gsv car interaction': 'car interaction',
    'crowd': 'group',
    'many people': 'people',
    'in wheelchair': 'on wheelchair',
    'using wheelchair': 'riding wheelchair',
    'phone interaction': 'using phone',
    'pushing stroller or shopping cart': 'pushing stroller or shopping cart',
    'pushing pram': 'pushing stroller',
    'sprinting': 'running',
    'purchasing': 'shopping',
    'buying': 'shopping',
    'sitting down': 'sitting',
    'sport activities': 'playing sports',
    'athletic activities': 'playing sports',
    'athletics': 'playing sports',
    'vendors': 'street vendors',
    'street seller': 'a street seller',
    'merchant': 'a merchant',
    'vendor': 'a vendor',
    'street vendor': 'a street vendor',
    'taking image': 'taking picture',
    'taking photo': 'taking picture',
    'taking photograph': 'taking picture',
    'speaking': 'talking',
    'conversing': 'chatting',
    'communicating': 'talking',
    'arguing': 'talking',
    'discussing': 'talking',
    'debating': 'talking',
    'dialoguing': 'talking',
    'conversing on phone': 'chatting on phone',
    'speaking on cellphone': 'talking on phone',
    'chatting on cellphone': 'chatting on phone',
    'talking on cellphone': 'talking on phone',
    'conversing on cellphone': 'chatting on phone',
    'communicating on phone': 'talking on phone',
    'speaking on phone': 'talking on phone',
    'communicating on cellphone': 'talking on phone',
    'waiting for bus': 'waiting for a bus',
    'waiting in bus station': 'waiting at bus station',
    'waiting for bus at bus station': 'waiting at bus station',
    'with cycle': 'with bicycle',
    'with coffee or drinks': 'with drink',
    'with coffee': 'with drink',
    'baby/infant': 'baby',
    'toddler': 'child',
    'newborn': 'infant',
    'crossing zebra crossing': 'crossing a street',
    'crossing crosswalk': 'crossing a street',
    'crossing pedestrian crossing': 'crossing a street',
    'duplication': 'duplicate',
    'old person': 'elderly',
    'aged': 'elderly',
    'elderly person': 'elderly',
    'old': 'elderly',
    'senior person': 'senior',
    'aged person': 'senior',
    'crutches': 'walking aids',
    'walking frame': 'walking aids',
    'mobility aids': 'walking aids',
    'walking aid': 'walking aids',
    'mobility aid': 'walking aids',
    'wheelchair': 'riding wheelchair',
    'walking cane': 'walking stick',
    'multiple labels': 'multi-label',
    'multiple label': 'multi-label',
    'uncertain': 'not sure',
    'unsure': 'not sure',
    'not sure/confusing': 'not sure',
    'guide dog': 'service dog',
    'public service/cleaning': 'public service',
    'community service': 'public service',
    'riding horse cart': 'riding horse carriage',
    'riding horse wagon': 'riding horse carriage',
    'riding horse vehicle': 'riding horse carriage',
    'riding horse buggy': 'riding horse carriage',
    'youth': 'teenager',
    'adolescent': 'teenager',
    'working with laptop': 'working on laptop',
    'working on desktop': 'working on computer',
    'working with computer': 'working on computer',
    'working/laptop': 'working on laptop',
    'working with desktop': 'working on computer',
    'police officer': 'police',
    'cop': 'police',
    'loading packages from truck': 'loading packages',
    'unloading packages from truck': 'unloading packages',
    'load packages from car': 'loading packages',
    'loading packages from vehicle': 'loading packages',
    'unloading packages from vehicle': 'unloading packages',
    'unload packages from car': 'unloading packages',
    'loading packages from car': 'loading packages',
    'unloading packages from car': 'unloading packages',
    'load/unload packages from car/truck': 'loading packages or unloading packages',
    'reading magazine': 'reading',
    'reading newspaper': 'reading',
    'reading journal': 'reading',
    'reading article': 'reading',
    'reading document': 'reading',
    'reading paper': 'reading',
    'reading text': 'reading',
    'reading publication': 'reading',
    'waiting for coffee or tea': 'waiting for food or drink',
    'waiting for food/drinks': 'waiting for food or drink',
    'waiting for food or beverage': 'waiting for food or drink',
    'waiting for drink or beverage': 'waiting for food or drink',
    'waiting for meal or snack': 'waiting for food or drink',
    'waiting for tea': 'waiting for food or drink',
    'waiting for coffee': 'waiting for food or drink',
    'waiting for drinks': 'waiting for food or drink',
    'waiting for snack': 'waiting for food or drink',
    'waiting for beverage': 'waiting for food or drink',
    'waiting for food or drink': 'waiting for food or drink',
    'waiting for meal': 'waiting for food or drink',
    'taking cab/taxi': 'taking taxi',
    'motorcycle riding': 'riding motorcycle',
    'riding motorbike': 'riding motorcycle',
    'motorbike riding': 'riding motorcycle',
    'motorbiking': 'riding motorcycle',
    'snuggling': 'hugging',
    'cuddling': 'hugging',
    'pushing cart': 'pushing a shopping cart',
    'pushing wheelchair': 'pushing a wheelchair',
    "playing with phone": "playing with a phone",
    "looking at phone": "looking at a phone",
    "engaged with phone": "engaged with a phone",
    'with cane or walker': 'with a cane or walker',
}

