subject = 0
verb = 2
prepositional = 1

subject = 'subject'
verb = 'verb'
prepositional = 'prepositional'

ORDER = {
    'alone': prepositional,
    'a person': subject,
    'person': subject,
    'individual': subject,
    'pedestrian': subject,
    'at petrol station': prepositional,
    'at gas station': prepositional,
    'biking': verb,
    'construction-workers': subject,
    'cycling': verb,
    'riding bike': verb,
    'bicycling': verb,
    'riding bicycle': verb,
    'laborers': subject,
    'builders': subject,
    'couple': subject,
    'two people': subject,
    'two pedestrians': subject,
    'two friends': subject,
    'dining': verb,
    'eating': verb,
    'snacking': verb,
    'GSV car interaction': subject,
    'car interaction': subject,
    'group': subject,
    'people': subject,
    'crowd': subject,
    'gathering': subject,
    'many people': subject,
    'on wheelchair': verb,
    'in wheelchair': verb,
    'using wheelchair': verb,
    'riding wheelchair': verb,
    'pet interactions': subject,
    'phone interaction': verb,
    'using phone': verb,
    'on phone': prepositional,
    'playing': verb,
    'pushing stroller': verb,
    'pushing shopping cart': verb,
    'pushing cart': verb,
    'pushing baby carriage': verb,
    'pushing baby stroller': verb,
    'pushing baby pram': verb,
    'pushing pram': verb,
    'pushing wheelchair': verb,
    'running': verb,
    'jogging': verb,
    'sprinting': verb,
    'shopping': verb,
    'buying': verb,
    'purchasing': verb,
    'browsing': verb,
    'sitting': verb,
    'seated': prepositional,
    'sitting down': verb,
    'sport activities': subject,
    'sports': verb,
    'playing sports': verb,
    'athletics': subject,
    'athletic activities': subject,
    'standing': verb,
    'street-vendors': subject,
    'vendors': subject,
    'taking photo': verb,
    'taking picture': verb,
    'taking photograph': verb,
    'taking image': verb,
    'photographing': verb,
    'talking': verb,
    'chatting': verb,
    'conversing': verb,
    'speaking': verb,
    'communicating': verb,
    'arguing': verb,
    'discussing': verb,
    'debating': verb,
    'dialoguing': verb,
    'talking on phone': verb,
    'talking on cellphone': verb,
    'chatting on phone': verb,
    'chatting on cellphone': verb,
    'conversing on phone': verb,
    'conversing on cellphone': verb,
    'speaking on phone': verb,
    'speaking on cellphone': verb,
    'communicating on phone': verb,
    'communicating on cellphone': verb,
    'waiting in bus station': verb,
    'waiting at bus station': verb,
    'waiting for bus': verb,
    'waiting for bus at bus station': verb,
    'walking': verb,
    'strolling': verb,
    'with bike': prepositional,
    'with bicycle': prepositional,
    'with cycle': prepositional,
    'with coffee or drinks': prepositional,
    'with coffee': prepositional,
    'with drink': prepositional,
    'with beverage': prepositional,
    'baby': subject,
    'infant': subject,
    'newborn': subject,
    'toddler': subject,
    'crossing crosswalk': verb,
    'crossing street': verb,
    'crossing road': verb,
    'crossing zebra crossing': verb,
    'crossing pedestrian crossing': verb,
    'duplicate': verb,
    'duplicated': prepositional,
    'duplication': subject,
    'elderly': subject,
    'old': subject,
    'senior': subject,
    'aged': subject,
    'aged person': subject,
    'old person': subject,
    'senior person': subject,
    'elderly person': subject,
    'kid': subject,
    'child': subject,
    'mobility aids': subject,
    'walking aids': subject,
    'walking stick': subject,
    'walking cane': subject,
    'crutches': subject,
    'wheelchair': subject,
    'walking frame': subject,
    'walking aid': subject,
    'mobility aid': subject,
    'model_hint': subject,
    'multi-label': subject,
    'multiple labels': subject,
    'multiple label': subject,
    'no people': subject,
    'not sure': prepositional,
    'confusing': prepositional,
    'unsure': prepositional,
    'uncertain': prepositional,
    'ambiguous': prepositional,
    'pet': subject,
    'service dog': subject,
    'guide dog': subject,
    'public service': subject,
    'community service': subject,
    'cleaning': verb,
    'riding carriage': verb,
    'riding horse carriage': verb,
    'riding horse cart': verb,
    'riding horse wagon': verb,
    'riding horse buggy': verb,
    'riding horse vehicle': verb,
    'teenager': subject,
    'teen': subject,
    'adolescent': subject,
    'youth': subject,
    'working on laptop': verb,
    'working with laptop': verb,
    'working on computer': verb,
    'working with computer': verb,
    'working on desktop': verb,
    'working with desktop': verb,
    'no interaction': subject,
    'police': subject,
    'law enforcement': subject,
    'police officer': subject,
    'cop': subject,
    'load packages from car': verb,
    'unload packages from car': verb,
    'loading packages': verb,
    'unloading packages': verb,
    'loading packages from car': verb,
    'unloading packages from car': verb,
    'loading packages from truck': verb,
    'unloading packages from truck': verb,
    'loading packages from vehicle': verb,
    'unloading packages from vehicle': verb,
    'reading': verb,
    'reading book': verb,
    'reading newspaper': verb,
    'reading magazine': verb,
    'reading paper': verb,
    'reading document': verb,
    'reading text': verb,
    'reading article': verb,
    'reading journal': verb,
    'reading publication': verb,
    'with luggage': prepositional,
    'with suitcase': prepositional,
    'waiting for food': verb,
    'waiting for drinks': verb,
    'waiting for drink': verb,
    'waiting for beverage': verb,
    'waiting for meal': verb,
    'waiting for snack': verb,
    'waiting for coffee': verb,
    'waiting for tea': verb,
    'waiting for food or drink': verb,
    'waiting for food or beverage': verb,
    'waiting for drink or beverage': verb,
    'waiting for meal or snack': verb,
    'waiting for coffee or tea': verb,
    'taking cab': verb,
    'taking taxi': verb,
    'picnic': subject,
    'picnicking': verb,
    'riding motorcycle': verb,
    'motorcycle riding': verb,
    'riding motorbike': verb,
    'motorbike riding': verb,
    'motorcycling': verb,
    'motorbiking': verb,
    'hugging': verb,
    'embracing': verb,
    'cuddling': verb,
    'snuggling': verb,
    'standing to cross crosswalk': verb,
    'sitting on bench or chair': verb,
    'with dog': prepositional,
    'with pet': prepositional,
}

